pipelines:
  branches:
    master: &default-step
      - step:
          script:
            - source conf/ci/anaconda.sh
            - install-anaconda
            - test-package python=2.7 MPI=mpich
            - test-package python=3.6 MPI=mpich
            - test-package python=2.7 MPI=openmpi
            - test-package python=3.6 MPI=openmpi
    maint: *default-step
  custom:
    default: *default-step
